<?php

// AUTO-GENERATED seed catalogue (source: public/assets/js/data.js)
// Do not edit by hand — regenerate via node scripts/extract_catalogue.js

return [
  'categories' => [
    ['slug' => 'corporate-gifts', 'name' => 'Corporate Gifts'],
    ['slug' => 'desk-office', 'name' => 'Desk & Office'],
    ['slug' => 'drinkware', 'name' => 'Drinkware'],
    ['slug' => 'apparel', 'name' => 'Branded Apparel'],
    ['slug' => 'tech-gadgets', 'name' => 'Tech & Gadgets'],
    ['slug' => 'event', 'name' => 'Event Essentials'],
  ],
  'products' => [
    [
      'slug' => 'signature-gift-box',
      'name' => 'The Signature Gift Box',
      'cat'  => 'corporate-gifts',
      'price' => 18500,
      'badge' => 'Bestseller',
      'img'  => '1503602642458-232111445657',
      'short' => 'A curated premium box of branded essentials — the perfect first impression for clients and VIPs.',
      'desc' => 'The Signature Gift Box is our flagship curation: a tactile, premium-branded box containing a selection of elegant desk and lifestyle essentials, finished with a personalised note card. Every box is assembled by hand in our Lagos atelier and can be tailored to a theme, season, or campaign. Ideal for client gifting, onboarding, and key-account retention.',
      'features' => ['Hand-assembled premium box','Fully customisable contents','Personalised note cards','Bulk & bespoke options'],
      'specs' => ['Contents' => '6 curated branded pieces','Customisation' => 'Full branding & theme','MOQ' => '20 units','Lead time' => '7–10 business days'],
    ],
    [
      'slug' => 'executive-watch',
      'name' => 'Executive Chrono Watch',
      'cat'  => 'corporate-gifts',
      'price' => 45000,
      'badge' => 'Premium',
      'img'  => '1578683010236-d716f9a3f461',
      'short' => 'A refined timepiece engraved with your brand — a lasting symbol of appreciation.',
      'desc' => 'A classic executive chronograph with a precision movement, sapphire-coated glass and a stainless case. The dial and back plate carry laser-engraved branding, making it a dignified recognition gift for long-serving staff, partners, and executive milestones.',
      'features' => ['Laser-engraved branding','Sapphire-coated glass','Gift-boxed presentation','1-year warranty'],
      'specs' => ['Movement' => 'Quartz chronograph','Case' => 'Stainless steel','Water resistance' => '3 ATM','MOQ' => '10 units'],
    ],
    [
      'slug' => 'leather-journal-set',
      'name' => 'Leather Journal & Pen Set',
      'cat'  => 'desk-office',
      'price' => 12500,
      'badge' => '',
      'img'  => '1531346878377-a5be20888e57',
      'short' => 'Embossed leather journal paired with a branded rollerball pen — quiet luxury for the desk.',
      'desc' => 'A supple leatherette journal with 192 pages of gilded-edge paper, paired with a weighty metal rollerball pen. Both pieces are debossed or foil-printed with your mark. A timeless desk essential that keeps your brand in daily use.',
      'features' => ['Debossed branding','192-page gilded journal','Matching rollerball pen','Individually boxed'],
      'specs' => ['Journal' => 'A5 · 192 pages','Material' => 'Vegan leather','Pen' => 'Rollerball, matte','MOQ' => '25 units'],
    ],
    [
      'slug' => 'insulated-bottle',
      'name' => 'Insulated Steel Bottle',
      'cat'  => 'drinkware',
      'price' => 9800,
      'badge' => 'Eco',
      'img'  => '1602143407151-7111542de6e8',
      'short' => 'Double-wall stainless bottle that keeps drinks cold for 24 hours — built for brand longevity.',
      'desc' => 'A 750ml double-wall vacuum bottle in brushed stainless or powder-coated colourways, laser-engraved or wrap-printed with your artwork. Keeps drinks cold 24 hours and hot 12 hours — a genuinely used, genuinely seen promotional piece.',
      'features' => ['24h cold / 12h hot','BPA-free & food-safe','Laser or wrap printing','Recyclable steel'],
      'specs' => ['Capacity' => '750ml','Material' => '18/8 stainless steel','Insulation' => 'Double-wall vacuum','MOQ' => '30 units'],
    ],
    [
      'slug' => 'classic-tee',
      'name' => 'Classic Signature Tee',
      'cat'  => 'apparel',
      'price' => 6500,
      'badge' => '',
      'img'  => '1521572163474-6864f9cf17ab',
      'short' => 'Combed-cotton crew tee in a range of colours, screen-printed with your brand.',
      'desc' => 'A 220gsm combed-cotton crew neck in a palette of brand-friendly colours. Screen, DTG, or embroidery options make it the workhorse of every activation, staff uniform, and event wardrobe.',
      'features' => ['Combed cotton 220gsm','Screen, DTG or embroidery','Unisex sizing XS–3XL','Colour-matched to your brand'],
      'specs' => ['Fabric' => '100% combed cotton','Weight' => '220gsm','Sizing' => 'XS–3XL','MOQ' => '50 units'],
    ],
    [
      'slug' => 'studio-headphones',
      'name' => 'Studio Wireless Headphones',
      'cat'  => 'tech-gadgets',
      'price' => 32000,
      'badge' => 'Premium',
      'img'  => '1505740420928-5e560c06d30e',
      'short' => 'Over-ear wireless sound with a debossed brand finish — tech your team will actually use.',
      'desc' => 'Over-ear wireless headphones with active noise cancellation, plush memory-foam earcups and 30-hour battery life. Delivered with a branded carry case and charging cable. A high-value gift that keeps your brand top-of-mind every day.',
      'features' => ['Active noise cancellation','30-hour battery','Branded carry case','Bluetooth 5.3'],
      'specs' => ['Battery' => '30 hours','Connectivity' => 'Bluetooth 5.3 / AUX','Charging' => 'USB-C','MOQ' => '10 units'],
    ],
    [
      'slug' => 'urban-backpack',
      'name' => 'Urban Commuter Backpack',
      'cat'  => 'event',
      'price' => 24000,
      'badge' => '',
      'img'  => '1553062407-98eeb64c6a62',
      'short' => 'Water-resistant laptop backpack with a 15" sleeve and discreet logo embroidery.',
      'desc' => 'A weather-proof commuter backpack with padded 15-inch laptop sleeve, anti-theft back pocket, and ergonomic straps. Your logo is embossed or embroidered for a refined, non-screaming brand statement — ideal for summits, conferences and employee kits.',
      'features' => ['15" laptop sleeve','Water-resistant shell','Discreet embroidery','Ergonomic back panel'],
      'specs' => ['Capacity' => '22L','Laptop' => 'Up to 15 inch','Material' => 'RPET nylon','MOQ' => '15 units'],
    ],
    [
      'slug' => 'ceramic-mug-set',
      'name' => 'Signature Mug Duo',
      'cat'  => 'drinkware',
      'price' => 5500,
      'badge' => '',
      'img'  => '1514228742587-6b1558fcca3d',
      'short' => 'Glossy bone-china mugs in a branded gift wrap — daily reminders of your mark.',
      'desc' => 'A pair of 350ml bone-china mugs with a glossy glaze and detailed logo print, presented in an elegant sleeve. The everyday desk companion that quietly reinforces your brand with every coffee.',
      'features' => ['Bone-china 350ml','Full-colour printing','Dishwasher & microwave safe','Branded sleeve'],
      'specs' => ['Capacity' => '350ml','Material' => 'Bone china','Care' => 'Dishwasher safe','MOQ' => '40 units'],
    ],
    [
      'slug' => 'signature-pen',
      'name' => 'Signature Rollerball Pen',
      'cat'  => 'desk-office',
      'price' => 3200,
      'badge' => '',
      'img'  => '1583485088034-697b5bc54ccd',
      'short' => 'A weighty metallic rollerball with engraved branding — the classic deal-closer.',
      'desc' => 'A precision-machined metallic rollerball in gold, silver or matte black, engraved with your logo. Refillable and supplied in a gift sleeve. The timeless instrument used at every signing, launch and milestone.',
      'features' => ['Precision-machined metal','Laser engraving','Refillable cartridge','Gift sleeve included'],
      'specs' => ['Material' => 'Alloy, plated','Finish' => 'Gold / silver / black','Ink' => 'Blue, refillable','MOQ' => '50 units'],
    ],
    [
      'slug' => 'branded-jacket',
      'name' => 'Branded Executive Jacket',
      'cat'  => 'apparel',
      'price' => 28000,
      'badge' => '',
      'img'  => '1591047139829-d91aecb6caea',
      'short' => 'Lightweight tailored jacket with embroidered branding — polish for staff and VIPs.',
      'desc' => 'A tailored, lightweight outer shell in a water-repellent fabric, finished with subtle chest embroidery. Cut for a professional silhouette, it elevates front-of-house teams, field staff and VIP guest appearances.',
      'features' => ['Water-repellent shell','Chest embroidery','Tailored fit','Windbreaker lining'],
      'specs' => ['Fabric' => 'Nylon blend, 120gsm','Sizing' => 'S–4XL','Finish' => 'Chest embroidery','MOQ' => '20 units'],
    ],
    [
      'slug' => 'smart-band',
      'name' => 'Activity Smart Band',
      'cat'  => 'tech-gadgets',
      'price' => 16000,
      'badge' => 'New',
      'img'  => '1546868871-7041f2a55e12',
      'short' => 'A health-focused smart band with a custom watch face — modern, useful, memorable.',
      'desc' => 'A slim fitness smart band with heart-rate, sleep and step tracking, a 14-day battery and an IP68 rating. Your logo is laser-printed on the strap and featured on a custom watch face. Perfect for wellness programmes and HR campaigns.',
      'features' => ['Heart-rate & sleep tracking','14-day battery','Custom watch face','IP68 water resistant'],
      'specs' => ['Display' => '1.1" AMOLED','Battery' => '14 days','Rating' => 'IP68','MOQ' => '20 units'],
    ],
    [
      'slug' => 'heritage-timepiece',
      'name' => 'Heritage Leather Watch',
      'cat'  => 'corporate-gifts',
      'price' => 52000,
      'badge' => 'Premium',
      'img'  => '1523275335684-37898b6baf30',
      'short' => 'A slim classic with a genuine leather strap and engraved case back.',
      'desc' => 'A slim, dress-focused timepiece with a genuine leather strap and a case back engraved with your mark. Supplied in a leather-grain presentation box with certificate. Reserved for the most significant recognition moments.',
      'features' => ['Genuine leather strap','Engraved case back','Presentation box','Certificate of authenticity'],
      'specs' => ['Movement' => 'Japanese quartz','Strap' => 'Genuine leather','Case' => '42mm alloy','MOQ' => '10 units'],
    ],
    [
      'slug' => 'corporate-hamper',
      'name' => 'Corporate Gift Hamper',
      'cat'  => 'corporate-gifts',
      'price' => 38000,
      'badge' => 'Bestseller',
      'img'  => '1549465220-1a8b9238cd48',
      'short' => 'A generous curated hamper of gourmet and premium goods — festive, festive, memorable.',
      'desc' => 'Our corporate hamper combines gourmet treats, fine teas, and premium branded keepsakes in an elegant crate. Built for festive seasons, client appreciation and end-of-year programmes, with full customisation of contents and packaging.',
      'features' => ['Curated gourmet contents','Premium branded crate','Personalised ribbon & card','Seasonal themes'],
      'specs' => ['Pieces' => '10–12 curated items','Packaging' => 'Wooden crate','Customisation' => 'Full branding','MOQ' => '10 units'],
    ],
    [
      'slug' => 'wireless-headset',
      'name' => 'True Wireless Earbuds',
      'cat'  => 'tech-gadgets',
      'price' => 14000,
      'badge' => '',
      'img'  => '1583394838336-acd977736f90',
      'short' => 'Compact true-wireless earbuds in a branded charging case.',
      'desc' => 'True-wireless earbuds with touch controls, deep bass and a pocketable charging case that carries your logo. An affordable, high-perceived-value tech gift for conferences, trade fairs and customer giveaways.',
      'features' => ['Touch controls','Charging case branding','Bluetooth 5.2','20h total playtime'],
      'specs' => ['Playtime' => '5h + 15h case','Connectivity' => 'Bluetooth 5.2','Charging' => 'USB-C','MOQ' => '30 units'],
    ],
  ],
];
